[project]
name = "compound-support-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Iman", email = "iman.vahdat@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "langchain-core>=1.6.3",
    "langchain-ollama>=1.1.0",
    "langgraph>=1.2.11",
    "pydantic>=2.13.5",
]

[project.scripts]
compound-support-agent = "compound_support_agent:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "ruff>=0.16.8",
]
