from typing import TypedDict


class AgentState(TypedDict):
    """
    The global state dictionary for the Compound Support Agent.
    Every node in the LangGraph reads from and writes to this state.
    """

    user_query: str  # The original ticket submitted by the customer
    intent: str | None  # Classification determined by the Router (Llama 3.2)
    database_facts: str | None  # Raw context pulled from MySQL based on the intent
    current_draft: (
        str | None
    )  # The proposed response generated by the Drafter (Qwen 14B)
    validation_status: (
        str | None
    )  # 'PASSED' or 'FAILED' determined by the Validator (Llama 3.2)
    loop_count: int  # Safety counter to prevent infinite hallucination loops
